main:
  push:
    - docker: 
        image: docker.cnb.cool/liyao52033/images/hugo-eo:latest
      imports: https://cnb.cool/liyao52033/envs/-/blob/main/private.yml
      stages: 

        - name: 创建跨仓库 PR
          image: cnbcool/create-pr:latest
          settings:
            # 必填：目标分支（当前仓库的分支）
            target_branch: main
            # 私有仓库的源分支（如不填默认用当前分支 CNB_BRANCH）
            head_branch: main
            # 跨仓库必填：私有仓库的 slug（格式 group_slug/repo_name）
            head_repo_slug: liyao52033/privatemd
            # PR 标题
            title: "【自动创建】私有仓库同步到主仓库"
            # PR 内容描述
            body: "此 PR 由流水线自动创建，用于将私有仓库的 temp-branch 合并到主仓库 main 分支"
            # 评审者（多个用逗号隔开）
            reviewers: "reviewer1,reviewer2"
            # 指派人（多个用逗号隔开）
            assignees: "assignee1"
            # PR 标签
            labels: "auto-pr,cross-repo"

        - name: install-dependencies
          script: |
            echo "Installing dependencies..."
            yarn
            echo "✅ 依赖安装完成"
        - name: build with hugo
          imports: https://cnb.cool/liyao52033/envs/-/blob/main/hugo-env.yml
          script: |
            export HUGO_PARAMS_DOCSEARCH_APPID=$HUGO_PARAMS_DOCSEARCH_APPID
            export HUGO_PARAMS_DOCSEARCH_APIKEY=$HUGO_PARAMS_DOCSEARCH_APIKEY
            export HUGO_PARAMS_DOCSEARCH_INDEXNAME=$HUGO_PARAMS_DOCSEARCH_INDEXNAME
            export HUGO_PARAMS_DOCSEARCH_ASKAI_INDEXNAME=$HUGO_PARAMS_DOCSEARCH_ASKAI_INDEXNAME
            export HUGO_PARAMS_DOCSEARCH_ASKAI_ASSISTANTID=$HUGO_PARAMS_DOCSEARCH_ASKAI_ASSISTANTID
            export HUGO_PARAMS_FOOTER_ICP=$HUGO_PARAMS_FOOTER_ICP
            node scripts/add-frontmatter.js
            yarn run build:log
        - name: deploy-to-edgeone-pages
          imports:  https://cnb.cool/liyao52033/envs/-/blob/main/envs.yml
          script: |
            echo "Deploying to EdgeOne Pages..."
            edgeone pages deploy ./dist -n vuepress-vdoing -t $EDGEONE_PAGES_API_TOKEN
        - name: prepare bg branch
          image: alpine/git
          commands:
            - git fetch origin main
            - git checkout -b bg origin/main
        - name: sync-to-github
          image: tencentcom/git-sync
          imports: https://cnb.cool/liyao52033/envs/-/blob/main/github-env.yml
          settings:
            target_url: https://github.com/liyao52033/hugopress.git
            branch: bg
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

include:
    - https://cnb.cool/liyao52033/build-template/-/blob/main/.cnb/vscode.yml
    - https://cnb.cool/liyao52033/build-template/-/blob/main/template/codewiki.yml